---
# Staging Environment Inventory
all:
  hosts:
    staging-attestor-01:
      ansible_host: <ip address of the vm>
      ansible_user: ubuntu
      ansible_ssh_private_key_file: <path to the private key file>
  vars:
    env: staging
    infrastructure_provider: aws  # Options: aws or gcp
    deployment_type: docker  # Options: docker or k8s
    region: us-east-1  # AWS region (e.g., us-east-1) or GCP region (e.g., us-central1)
    ansible_user: ubuntu
    gcp_project: <gcp project id>  # Required if infrastructure_provider is gcp

