apiVersion: v1
kind: ConfigMap
metadata:
  name: attestor-config
data:
  attestor_name: {{ .Values.attestor_name }}
  aleo_chain_id: "{{ .Values.aleo_chain_id }}"
  aleo_wallet_address: "{{ .Values.aleo_wallet_address }}"
  bsc_chain_id: "{{ .Values.bsc_chain_id }}"
  bsc_wallet_address: "{{ .Values.bsc_wallet_address }}"
  bsc_bridge_contract: "{{ .Values.bsc_bridge_contract }}"
  bsc_node_url: "{{ .Values.bsc_node_url }}"
  bsc_filter_topic: "{{ .Values.bsc_filter_topic }}"
  bsc_start_height: "{{ .Values.bsc_start_height }}"
  holesky_chain_id: "{{ .Values.bsc_chain_id }}"
  holesky_wallet_address: "{{ .Values.bsc_wallet_address }}"
  holesky_bridge_contract: "{{ .Values.bsc_bridge_contract }}"
  holesky_node_url: "{{ .Values.bsc_node_url }}"
  holesky_filter_topic: "{{ .Values.bsc_filter_topic }}"
  holesky_start_height: "{{ .Values.bsc_start_height }}"
  collector_service_url: "{{ .Values.collector_service_url }}"
  prometheus_pushgateway_url: "{{ .Values.prometheus_pushgateway_url }}"
