chainService:
  name: <releaseIdentifier>_attestor_verulink_<yourCompanyIdentifier>
  version: "1.0.1"
  chains:
    aleo:
      chain_id: "6694886634401"
      chain_type: aleo
      wallet_address: <aleo_wallet_address> # wallet indentifier
      bridge_contract: vlink_token_bridge_v3.aleo
      node_url: https://api.explorer.provable.com/v1|mainnet
      sequence_num_start:
        bsc: 370
        ethereum: 1607
        arbitrum: 1
        base: 1
      retry_packet_wait_dur: 2m0s
      prune_base_seq_num_wait_dur: 5m0s
      average_block_gen_dur: 3s
      dest_chains:
        bsc:
          pkt_validity_wait_dur: 15m0s
          finality_height: 23
        base:
          pkt_validity_wait_dur: 15m0s
          finality_height: 23
        ethereum:
          pkt_validity_wait_dur: 15m0s
          finality_height: 23
        arbitrum:
          pkt_validity_wait_dur: 15m0s
          finality_height: 23
    bsc:
      chain_id: "422842677816"
      chain_type: evm
      wallet_address: <your_evm_wallet_address>
      bridge_contract: 0xdeEbcF78DfDa7494f9Bbe4Ca313C486D29F0EC56
      node_url: wss://bsc-rpc.publicnode.com
      filter_topic: 0x2ea0473a63d92d3182c86a6f05d1984a63782c7c58f5d32bb629fdf43388c1b0

      retry_packet_wait_dur: 1m0s
      prune_base_seq_num_wait_dur: 1m0s
      average_block_gen_dur: 2s

      dest_chains:
        aleo:
          pkt_validity_wait_dur: 1m0s
          finality_height: 21
          feed_pkt_wait_dur: 1m0s
          start_height: 1

    base:
      chain_id: "27691695965085957"
      chain_type: evm
      wallet_address: <your_evm_wallet_address>
      bridge_contract: 0x1e12776edb78A5473964cF257E825991ad501533
      node_url: wss://base-rpc.publicnode.com
      filter_topic: 0x2ea0473a63d92d3182c86a6f05d1984a63782c7c58f5d32bb629fdf43388c1b0
      disabled: false

      retry_packet_wait_dur: 1m0s
      prune_base_seq_num_wait_dur: 1m0s
      average_block_gen_dur: 2s

      dest_chains:
        aleo:
          pkt_validity_wait_dur: 1560m0s
          finality_height: 450
          feed_pkt_wait_dur: 1m0s
          start_height: 35024395
          instant_pkt_wait_dur: 15m0s

    arbitrum:
      chain_id: "27428839738746033"
      chain_type: evm
      wallet_address: <your_evm_wallet_address>
      bridge_contract: 0x397e47F5072B48681b170199551bdB7fBDa136b7
      node_url: wss://arbitrum.drpc.org
      filter_topic: 0x2ea0473a63d92d3182c86a6f05d1984a63782c7c58f5d32bb629fdf43388c1b0
      disabled: false

      retry_packet_wait_dur: 1m0s
      prune_base_seq_num_wait_dur: 1m0s
      average_block_gen_dur: 250ms

      dest_chains:
        aleo:
          pkt_validity_wait_dur: 1560m0s
          finality_height: 3600
          feed_pkt_wait_dur: 1m0s
          start_height: 224887156
          instant_pkt_wait_dur: 15m0s

    ethereum:
      chain_id: "27234042785"
      chain_type: evm
      wallet_address: <your_evm_wallet_address>
      bridge_contract: 0x7440176A6F367D3Fad1754519bD8033EAF173133
      node_url: https://eth.llamarpc.com
      filter_topic: 0x2ea0473a63d92d3182c86a6f05d1984a63782c7c58f5d32bb629fdf43388c1b0
      disabled: false

      retry_packet_wait_dur: 1m0s
      prune_base_seq_num_wait_dur: 1m0s
      average_block_gen_dur: 12s

      dest_chains:
        aleo:
          pkt_validity_wait_dur: 1560m0s
          finality_height: 75
          feed_pkt_wait_dur: 1m0s
          start_height: 9847133
          instant_pkt_wait_dur: 15m0s

  check_health_service: 1m
  db_dir: /var/lib/attestor/prod
  consume_packet_workers: 20

  log:
    encoding: console
    rotation:
      max_size: 100
      max_age: 14
      max_backups: 10
      compress: true
    output_paths:
      - /var/log/attestor/dev
      - stdout

  mode: prod

  signing_service:
    host: signingservice
    port: 8080
    endpoint: /sign
    scheme: http
    username: aleo
    password: chain
    health_end_point: /health

  collector_service:
    uri: <collector_service_url>
    collector_wait_dur: 1h
    ca_certificate: /configs/.mtls/ca.crt
    attestor_certificate: /configs/.mtls/<releaseIdentifier>_attestor_verulink_<yourCompanyIdentifier>.crt
    attestor_key: /configs/.mtls/<releaseIdentifier>_attestor_verulink_<yourCompanyIdentifier>.key

  metrics:
    host: <prometheus_pushgateway_url>
    job_name: prod-push-gateway-v200
    
secrets:
  existingSecretName: attestor-secret

storage:
  type: pvc  # Options: "emptyDir", "pvc", "hostPath"
  # hostPathBase: /tmp/verulink-attestor
  
  # Create a new StorageClass (optional - set to true to create via Helm)
  createStorageClass: false
  storageClassName: "attestor-storage-class-prod"  # Name of the storage class to create
  provisioner: "ebs.csi.aws.com"  # Storage provisioner (ebs.csi.aws.com for AWS EBS)
  reclaimPolicy: "Retain"  # Options: "Delete" or "Retain" - Retain for production data safety
  volumeBindingMode: "WaitForFirstConsumer"  # Options: "Immediate" or "WaitForFirstConsumer"
  allowVolumeExpansion: true  # Allow volume expansion
  # Storage class parameters (for AWS EBS)
  parameters:
    type: gp3  # EBS volume type: gp2, gp3, io1, io2, st1, sc1
    fsType: ext4  # Filesystem type
    # encrypted: "true"  # Enable encryption (optional)
    # iops: "3000"  # IOPS for gp3/io1/io2 (optional)
    # throughput: "125"  # Throughput in MiB/s for gp3 (optional)
  
  # PVC configuration
  pvc:
    size: 10Gi  # Storage size for production (e.g., "10Gi", "50Gi", "100Gi")
    storageClassName: "attestor-storage-class-prod"  # Using existing storage class
    accessModes:  # Access modes
      - ReadWriteOnce

image:
  chain:
    repository: venture23/verulink-attestor-chain
    tag: v2.0.2
  sign:
    repository: venture23/verulink-attestor-sign
    tag: v2.0.2
