chainService:
  name: dev_attestor_verulink_v23
  version: "1.0.1"
  chains:
    aleo:
    chain_id: "6694886634403"
    chain_type: aleo
    wallet_address: aleo1eslxvrgwtev68t9y6l0nxtts86exewrucgj33aw309k20tch45ps6pex24 # wallet indentifier
    bridge_contract: vlink_token_bridge_v9.aleo
    node_url: https://api.explorer.provable.com/v1|testnet
    sequence_num_start:
      bsc: 1
      ethereum: 1
      arbitrum: 1
      base: 1
    retry_packet_wait_dur: 2m0s
    prune_base_seq_num_wait_dur: 5m0s
    average_block_gen_dur: 3s
    dest_chains:
      bsc:
        pkt_validity_wait_dur: 15m0s
        finality_height: 23
      base:
        pkt_validity_wait_dur: 15m0s
        finality_height: 23
      ethereum:
        pkt_validity_wait_dur: 15m0s
        finality_height: 23
      arbitrum:
        pkt_validity_wait_dur: 15m0s
        finality_height: 23
    bsc:
      chain_id: "28556963657430695"
      chain_type: evm
      wallet_address: 0x832894550007b560bd35d28ce564c2ccd690318f
      bridge_contract: 0xdeEbcF78DfDa7494f9Bbe4Ca313C486D29F0EC56
      node_url: wss://base-sepolia-rpc.publicnode.com
      filter_topic: 0x2ea0473a63d92d3182c86a6f05d1984a63782c7c58f5d32bb629fdf43388c1b0

      retry_packet_wait_dur: 1m0s
      prune_base_seq_num_wait_dur: 1m0s
      average_block_gen_dur: 2s

      dest_chains:
        aleo:
          pkt_validity_wait_dur: 1m0s
          finality_height: 21
          feed_pkt_wait_dur: 1m0s
          start_height: 1

    base:
      chain_id: "443067135441324596"
      chain_type: evm
      wallet_address: 0x832894550007b560bd35d28ce564c2ccd690318f
      bridge_contract: 0x1e12776edb78A5473964cF257E825991ad501533
      node_url: wss://base-sepolia-rpc.publicnode.com
      start_height: 35024395
      finality_height: 7050
      filter_topic: 0x2ea0473a63d92d3182c86a6f05d1984a63782c7c58f5d32bb629fdf43388c1b0
      disabled: false

      retry_packet_wait_dur: 1m0s
      prune_base_seq_num_wait_dur: 1m0s
      average_block_gen_dur: 12s

      dest_chains:
        aleo:
          pkt_validity_wait_dur: 1560m0s
          finality_height: 75
          feed_pkt_wait_dur: 1m0s
          start_height: 35024395
          instant_pkt_wait_dur: 15m0s

    arbitrum:
      chain_id: "438861435819683566"
      chain_type: evm
      wallet_address: 0x832894550007b560bd35d28ce564c2ccd690318f
      bridge_contract: 0x2E8e59559F3F0e1b49484F5f5C7d30b0017b543b
      node_url: wss://arbitrum-sepolia.drpc.org
      start_height: 224887156
      finality_height: 7050
      filter_topic: 0x2ea0473a63d92d3182c86a6f05d1984a63782c7c58f5d32bb629fdf43388c1b0
      disabled: false

      retry_packet_wait_dur: 1m0s
      prune_base_seq_num_wait_dur: 1m0s
      average_block_gen_dur: 12s

      dest_chains:
        aleo:
          pkt_validity_wait_dur: 1560m0s
          finality_height: 75
          feed_pkt_wait_dur: 1m0s
          start_height: 224887156
          instant_pkt_wait_dur: 15m0s

    ethereum:
      chain_id: "27234042785"
      chain_type: evm
      wallet_address: 0x832894550007b560bd35d28ce564c2ccd690318f
      bridge_contract: 0x7440176A6F367D3Fad1754519bD8033EAF173133
      node_url: https://eth.llamarpc.com
      start_height: 9847133
      finality_height: 7050
      filter_topic: 0x2ea0473a63d92d3182c86a6f05d1984a63782c7c58f5d32bb629fdf43388c1b0
      disabled: false

      retry_packet_wait_dur: 1m0s
      prune_base_seq_num_wait_dur: 1m0s
      average_block_gen_dur: 12s

      dest_chains:
        aleo:
          pkt_validity_wait_dur: 1560m0s
          finality_height: 75
          feed_pkt_wait_dur: 1m0s
          start_height: 9847133
          instant_pkt_wait_dur: 15m0s

  check_health_service: 1m
  db_dir: /var/lib/attestor/dev
  consume_packet_workers: 10

  log:
    encoding: console
    rotation:
      max_size: 100
      max_age: 14
      max_backups: 10
      compress: true
    output_paths:
      - /var/log/attestor/dev
      - stdout

  mode: stag

  signing_service:
    host: signingservice
    port: 8080
    endpoint: /sign
    scheme: http
    username: aleo
    password: chain
    health_end_point: /health

  collector_service:
    uri: https://aleomtls.venture23.xyz/
    collector_wait_dur: 1h
    ca_certificate: /configs/.mtls/ca.crt
    attestor_certificate: /configs/.mtls/dev_attestor_verulink_v23.crt
    attestor_key: /configs/.mtls/dev_attestor_verulink_v23.key

  metrics:
    host: https://pushgateway-aleomtls.venture23.xyz/
    job_name: dev-push-gateway
    
secrets:
  existingSecretName: attestor-secret

storage:
  type: emptyDir
  # hostPathBase: /tmp/verulink-attestor

image:
  chain:
    repository: venture23/verulink-attestor-chain
    tag: staging-v2.0.0-beta1
  sign:
    repository: venture23/verulink-attestor-sign
    tag: staging-v2.0.0-beta1
