---
# Handlers for docker role
- name: restart docker
  systemd:
    name: docker
    state: restarted

- name: restart attestor services
  command: docker compose -f {{ attestor_install_dir }}/compose.yml restart
  become_user: "{{ ansible_user }}"

- name: reload attestor services
  command: docker compose -f {{ attestor_install_dir }}/compose.yml up -d
  become_user: "{{ ansible_user }}"

