---
# Devnet Environment Inventory
all:
  hosts:
    devnet-attestor-01:
      ansible_host: 44.211.22.125
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ./attestor-deployment-ansible.pem
  vars:
    env: devnet
    infrastructure_provider: aws  # Options: aws or gcp
    deployment_type: docker  # Options: docker or k8s
    region: us-east-1  # AWS region (e.g., us-east-1) or GCP region (e.g., us-central1)
    ansible_user: ubuntu
    # gcp_project: <gcp-project-id>  # Required if infrastructure_provider is gcp

