---
# Mainnet Environment Variables for Attestor Service

# Attestor Configuration
mode: "prod"

# Aleo Chain Configuration
aleo_chain_id: "6694886634401"
aleo_wallet_address: "<your_aleo_wallet_address>"
aleo_bridge_contract: "vlink_token_bridge_v3.aleo"
aleo_node_url: "https://api.explorer.provable.com/v1|mainnet"
aleo_private_key: "<your_aleo_private_key>"

# BSC Chain Configuration
bsc_chain_id: "422842677816"  # BSC Mainnet
bsc_wallet_address: "<your_evm_wallet_address>"
bsc_bridge_contract: "0x397e47F5072B48681b170199551bdB7fBDa136b7"
bsc_node_url: "<bsc_rpc_url>"
bsc_start_height: "71865844"

# Ethereum Chain Configuration
ethereum_chain_id: "27234042785" # Ethereum Mainnet
ethereum_bridge_contract: "0x7440176A6F367D3Fad1754519bD8033EAF173133"
ethereum_node_url: "<ethereum_rpc_url>"
ethereum_start_height: "24026263"



# Base Chain Configuration
base_chain_id: "27691695965085957"  # Base Mainnet
base_bridge_contract: "0x397e47F5072B48681b170199551bdB7fBDa136b7"
base_node_url: "<base_rpc_url>"
base_start_height: "39558981"

# Arbitrum Chain Configuration
arbitrum_chain_id: "27428839738746033"  # Arbitrum Mainnet
arbitrum_bridge_contract: "0x397e47F5072B48681b170199551bdB7fBDa136b7"
arbitrum_node_url: "<arbitrum_rpc_url>"
arbitrum_start_height: "415778885"

# Service Configuration
deploy_dir: "/home/ubuntu/verulink_attestor"  # Deployment directory on target host
db_dir: "/var/lib/attestor/mainnet"
log_dir: "/var/log/attestor/mainnet"

# Signing Service Configuration
signing_service_host: "signingservice"
signing_service_port: 8080
signing_service_username: "<your_signing_service_username>"
signing_service_password: "<your_signing_service_password>"

# Collector Service Configuration
collector_service_url: "<collector_service_url>"
ca_certificate_base64: "<ca_certificate_base64>"
attestor_certificate_base64: "<attestor_certificate_base64>"
attestor_key_base64: "<attestor_key_base64>"

# Metrics Configuration
prometheus_pushgateway_url: "<prometheus_pushgateway_url>"
prometheus_job_name: "prod-push-gateway-v200"

# Docker Image Tags
docker_image_tag_sign: "v2.0.1"
docker_image_tag_chain: "v2.0.1"
deployment_environment: "prod"
