---
# Mainnet Environment Variables for Attestor Service

# Attestor Configuration
# attestor_name: "<releaseIdentifier>_attestor_verulink_<yourCompanyIdentifier>"
mode: "prod"

# Aleo Chain Configuration
aleo_chain_id: "6694886634401" # Aleo Mainnet
aleo_bridge_contract: "vlink_token_bridge_v3.aleo"
aleo_node_url: "https://api.explorer.provable.com/v1|mainnet"


# BSC Chain Configuration
bsc_chain_id: "422842677816"  # BSC Mainnet
bsc_bridge_contract: "0x397e47F5072B48681b170199551bdB7fBDa136b7"
bsc_node_url: "https://bnb-mainnet.g.alchemy.com/v2/nMksy96jdqlj0Mch3hcw3"
bsc_start_height: "71865844"

# Ethereum Chain Configuration
ethereum_chain_id: "27234042785" # Ethereum Mainnet
ethereum_bridge_contract: "0x7440176A6F367D3Fad1754519bD8033EAF173133"
ethereum_node_url: "https://eth-mainnet.g.alchemy.com/v2/xcyICrE5BUkbBiJKGOk5Y"
ethereum_start_height: "24026263"



# Base Chain Configuration
base_chain_id: "27691695965085957"  # Base Mainnet
base_bridge_contract: "0x397e47F5072B48681b170199551bdB7fBDa136b7"
base_node_url: "https://base-mainnet.g.alchemy.com/v2/xcyICrE5BUkbBiJKGOk5Y"
base_start_height: "39558981"


# Service Configuration
deploy_dir: "/home/ubuntu/verulink_attestor"  # Deployment directory on target host
db_dir: "/var/lib/attestor/mainnet"
log_dir: "/var/log/attestor/mainnet"

# Signing Service Configuration
signing_service_host: "signingservice"
signing_service_port: 8080


# Collector Service Configuration
collector_service_url: "https://dbservice-mainnet-mtls.verulink.com/"


# Metrics Configuration
prometheus_pushgateway_url: "https://prometheus-node-b-mainnet-mtls.verulink.com"
prometheus_job_name: "prod-push-gateway-v200"

# Docker Image Tags
docker_image_tag_sign: "v2.0.1"
docker_image_tag_chain: "v2.0.1"
deployment_environment: "prod"