---
# Mainnet Environment Variables for Attestor Service

# Attestor Configuration
# attestor_name: "<releaseIdentifier>_attestor_verulink_<yourCompanyIdentifier>"
mode: "prod"

# Aleo Chain Configuration
aleo_chain_id: "6694886634401" # Aleo Mainnet
aleo_bridge_contract: "vlink_token_bridge_v3.aleo"
aleo_node_url: "https://api.explorer.provable.com/v1|mainnet"
aleo_private_key: "<your_aleo_private_key>"

# BSC Chain Configuration
bsc_chain_id: "422842677816"  # BSC Mainnet
bsc_bridge_contract: ""
bsc_node_url: "<bsc_rpc_url>"
bsc_start_height: "<bsc_start_height>"

# Ethereum Chain Configuration
ethereum_chain_id: "27234042785" # Ethereum Mainnet
ethereum_bridge_contract: ""
ethereum_node_url: "<ethereum_rpc_url>"
ethereum_start_height: "<ethereum_start_height>"



# Base Chain Configuration
base_chain_id: ""  # Base Mainnet
base_bridge_contract: ""
base_node_url: "<base_rpc_url>"
base_filter_topic: ""
base_start_height: "<base_start_height>"

# Arbitrum Chain Configuration
arbitrum_chain_id: ""  # Arbirum Mainnet
arbitrum_bridge_contract: ""
arbitrum_node_url: ""
arbitrum_filter_topic: ""
arbitrum_start_height: "<arbitrum_start_height>"

# Service Configuration
deploy_dir: "/home/ubuntu/verulink_attestor"  # Deployment directory on target host
db_dir: "/var/lib/attestor/mainnet"
log_dir: "/var/log/attestor/mainnet"

# Signing Service Configuration
signing_service_host: "signingservice"
signing_service_port: 8080


# Collector Service Configuration
collector_service_url: "<collector_service_url>"


# Metrics Configuration
prometheus_pushgateway_url: "<prometheus_pushgateway_url>"
prometheus_job_name: "prod-push-gateway-v200"

# Docker Image Tags
docker_image_tag_sign: "v2.0.1"
docker_image_tag_chain: "v2.0.1"
deployment_environment: "prod"
