---
# Staging Environment Variables for Attestor Service

# Attestor Configuration
attestor_name: "stg_attestor_verulink_v23"
mode: "stage"

# Aleo Chain Configuration
aleo_chain_id: "6694886634403"
aleo_bridge_contract: "vlink_token_bridge_v9.aleo"
aleo_node_url: "https://api.explorer.provable.com/v1|testnet"

# BSC Chain Configuration
bsc_chain_id: "422842677857"  # BSC Testnet
bsc_bridge_contract: "0x2E8e59559F3F0e1b49484F5f5C7d30b0017b543b"
bsc_node_url: "wss://base-sepolia-rpc.publicnode.com"
bsc_filter_topic: "0x2ea0473a63d92d3182c86a6f05d1984a63782c7c58f5d32bb629fdf43388c1b0"
bsc_start_height: 77777

# Ethereum Chain Configuration
ethereum_chain_id: "27234042785"
ethereum_bridge_contract: "0x7440176A6F367D3Fad1754519bD8033EAF173133"
ethereum_node_url: "https://eth.llamarpc.com"
ethereum_start_height: 23813425


# Service Configuration
db_dir: "/var/lib/attestor/staging"
log_dir: "/var/log/attestor/staging"

# Signing Service Configuration
signing_service_host: "signingservice"
signing_service_port: 8080


# Collector Service Configuration
collector_service_url: "https://aleomtls.venture23.xyz/"

# Metrics Configuration
prometheus_pushgateway_url: "https://pushgateway-aleomtls.venture23.xyz/"
prometheus_job_name: "staging-push-gateway"

# Docker Image Tags
docker_image_tag_sign: "staging-v2.0.0-beta1"
docker_image_tag_chain: "staging-v2.0.0-beta1"
deployment_environment: "staging"
