name: Run Go Unit Tests

on:
  push:
    branches:
      - main
    paths:
      - "attestor/**"
  pull_request:
    paths:
      - "attestor/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Go
      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      # Cache Go modules
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-${{ runner.os }}-

      # chainService module
      - name: Download dependencies - chainService
        working-directory: attestor/chainService
        run: go mod download

      - name: Clean Go test cache - chainService
        working-directory: attestor/chainService
        run: go clean -testcache

      - name: Run tests - chainService
        working-directory: attestor/chainService
        run: go test ./...

      # signingService module
      - name: Download dependencies - signingService
        working-directory: attestor/signingService
        run: go mod download

      - name: Clean Go test cache - signingService
        working-directory: attestor/signingService
        run: go clean -testcache

      - name: Run tests - signingService
        working-directory: attestor/signingService
        run: go test ./...
